// Generated by CoffeeScript 1.9.1
var Task, TodoList;

Task = (function() {
  function Task() {}

  return Task;

})();

TodoList = (function() {
  function TodoList(ele) {
    this.list = [];
    this.ele = ele;
  }

  TodoList.prototype.render = function() {
    return console.log(this.list);
  };

  return TodoList;

})();
